version: "3"
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices_network

  service-discovery-container:
    image: ghcr.io/davidone007/service-discovery:${BRANCH_TAG}
    ports:
      - 8761:8761
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  cloud-config-container:
    image: ghcr.io/davidone007/cloud-config:${BRANCH_TAG}
    ports:
      - 9296:9296
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/

  api-gateway-container:
    image: ghcr.io/davidone007/api-gateway:${BRANCH_TAG}
    ports:
      - 8080:8080
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=api-gateway-container
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=false
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER-CASE-SERVICE-ID=true
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - zipkin-container

  proxy-client-container:
    image: ghcr.io/davidone007/proxy-client:${BRANCH_TAG}
    ports:
      - 8900:8900
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=proxy-client-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  order-service-container:
    image: ghcr.io/davidone007/order-service:${BRANCH_TAG}
    ports:
      - 8300:8300
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=order-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  payment-service-container:
    image: ghcr.io/davidone007/payment-service:${BRANCH_TAG}
    ports:
      - 8400:8400
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=payment-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  product-service-container:
    image: ghcr.io/davidone007/product-service:${BRANCH_TAG}
    ports:
      - 8500:8500
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=product-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  shipping-service-container:
    image: ghcr.io/davidone007/shipping-service:${BRANCH_TAG}
    ports:
      - 8600:8600
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=shipping-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  user-service-container:
    image: ghcr.io/davidone007/user-service:${BRANCH_TAG}
    ports:
      - 8700:8700
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=user-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

  favourite-service-container:
    image: ghcr.io/davidone007/favourite-service:${BRANCH_TAG}
    ports:
      - 8800:8800
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_FETCH-REGISTRY=true
      - EUREKA_INSTANCE_PREFER-IP-ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=favourite-service-container
      - RIBBON_EUREKA_ENABLED=true
    depends_on:
      - service-discovery-container
      - cloud-config-container

networks:
  microservices_network:
    driver: bridge
