apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: cloud-config-container
  name: cloud-config-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloud-config-container
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/generated/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: cloud-config-container
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin-container:9411
          image: selimhorri/cloud-config-ecommerce-boot:0.1.0
          name: cloud-config-container
          ports:
            - containerPort: 9296
              protocol: TCP
      restartPolicy: Always
