apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: favourite-service-container
  name: favourite-service-container
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    io.kompose.service: favourite-service-container
