apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: order-service-container
  name: order-service-container
spec:
  ports:
    - name: "8300"
      port: 8300
      targetPort: 8300
  selector:
    io.kompose.service: order-service-container
