apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: shipping-service-container
  name: shipping-service-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping-service-container
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/generated/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: shipping-service-container
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: shipping-service-container
            - name: EUREKA_INSTANCE_PREFER-IP-ADDRESS
              value: "false"
            - name: RIBBON_EUREKA_ENABLED
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config-container:9296/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin-container:9411
          image: selimhorri/shipping-service-ecommerce-boot:0.1.0
          name: shipping-service-container
          ports:
            - containerPort: 8600
              protocol: TCP
      restartPolicy: Always
