apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: shipping-service-container
  name: shipping-service-container
spec:
  ports:
    - name: "8600"
      port: 8600
      targetPort: 8600
  selector:
    io.kompose.service: shipping-service-container
