apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/generated/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: user-service-container
  name: user-service-container
spec:
  ports:
    - name: "8700"
      port: 8700
      targetPort: 8700
  selector:
    io.kompose.service: user-service-container
