{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      {{- if $val.initContainers }}
      initContainers:
        {{- toYaml $val.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $val.name }}
          {{- if $val.fullImage }}
          image: "{{ $val.image }}"
          {{- else }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $val.image }}:{{ default $.Values.global.imageTag $val.tag }}"
          {{- end }}
          ports:
            - containerPort: {{ $val.port }}
              protocol: TCP
          env:
            {{- toYaml $val.env | nindent 12 }}
      restartPolicy: Always
{{- end }}
