{{- range $key, $val := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.name }}
  labels:
    app: {{ $val.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $val.name }}
  template:
    metadata:
      labels:
        app: {{ $val.name }}
    spec:
      {{- if $val.initContainers }}
      initContainers:
        {{- toYaml $val.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $val.name }}
          {{- if $val.fullImage }}
          image: "{{ $val.image }}"
          {{- else }}
          image: "{{ $.Values.global.imageRegistry }}/{{ $val.image }}:{{ default $.Values.global.imageTag $val.tag }}"
          {{- end }}
          imagePullPolicy: {{ default "IfNotPresent" $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $val.port }}
              protocol: TCP
          env:
            {{- toYaml $val.env | nindent 12 }}
          {{- if and $.Values.keyVault.enabled (eq $val.name "proxy-client-container") }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          {{- end }}
      {{- if and $.Values.keyVault.enabled (eq $val.name "proxy-client-container") }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
      {{- end }}
      restartPolicy: Always
{{- end }}