{{- if .Values.secrets.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
  {{- range .Values.secrets.objects }}
  - secretName: {{ .secretName }}
    type: Opaque
    data:
    {{- range .data }}
    - objectName: {{ .objectName }}
      key: {{ .key }}
    {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" 
    keyvaultName: {{ .Values.secrets.keyVaultName }}
    cloudName: ""
    objects: |
      array:
        {{- range .Values.secrets.objects }}
        {{- range .data }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
        {{- end }}
    tenantId: {{ .Values.secrets.tenantId }}
{{- end }}
