{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
  - secretName: jwt-secret-csi
    type: Opaque
    data:
    - objectName: jwt-secret
      key: jwt-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.keyVault.tenantId | quote }}
{{- end }}
