apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: zipkin-container
  name: zipkin-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-container
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: zipkin-container
    spec:
      containers:
        - image: openzipkin/zipkin
          name: zipkin-container
          ports:
            - containerPort: 9411
              protocol: TCP
      restartPolicy: Always
